name: Update Org Navigation
on:
  schedule:
    # Every day at 12
    - cron: '0 12 * * *'
  workflow_dispatch
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # Disable automatic npm caching if not required
      - run: gh repo ls S2outh --json name,url,description,repositoryTopics | node scripts/write-readme.js
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
